### ISSUE TITLE
CLI client: disable too restrictive checks

### ISSUE THREAD

**Issue by mhamrle** [Open-Transactions/opentxs#526]
Current CLI client checks if all nyms passed by params exists on client. This is not always required (for example checknym)

**Comment by FellowTraveler** [comment]
There are two types of Nyms. Private Nyms that are in your wallet, and public nyms that are in your address book.

Private Nyms can be addressed by the ID, or partial ID, or label. They must be present in the wallet. Whereas public nyms can only be addressed by a FULL ID. If a public nym is not found locally, it can be downloaded from the server.

**Comment by haarts** [comment]
@mhamrle is this fixed now?

**Comment by mhamrle** [comment]
No, this is not fixed. #527 fixed only some commands, not everything.
